---
- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: true

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Deploy Nginx configuration for Redis
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/redis
  become: true

- name: Create symbolic link for Nginx configuration
  file:
    src: /etc/nginx/sites-available/redis
    dest: /etc/nginx/sites-enabled/redis
    state: link
  become: true

- name: Test Nginx configuration
  command: nginx -t
  become: true

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  become: true
