---

- name: Update apt cache for Debian-based systems
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'
  
# tasks file for redis_role
- name: Ensure Redis is installed
  package:
    name: "{{ redis_package }}"
    state: present
  when: ansible_os_family in ['Debian', 'RedHat']

- name: Install Redis on Debian-based systems
  apt:
    name: redis-server
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Redis on RedHat-based systems
  yum:
    name: redis
    state: present
  when: ansible_os_family == 'RedHat'

- name: Configure Redis
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
  notify:
    - restart redis

- name: Ensure Redis service is running
  service:
    name: redis
    state: started
    enabled: yes

